{
 "title": "k8s dashboard",
 "tags": [
  "k8s",
  "node",
  "monitoring"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Namespaces - Ready ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  min by (namespace) (\n    kube_pod_status_ready{condition=\"true\", namespace=~\"gpu|service|db\"}\n    and on (namespace,pod)\n    (kube_pod_status_phase{phase=\"Running\", namespace=~\"gpu|service|db\"} == 1)\n  ) == bool 1\n)\n* on (namespace)\n(\n  count by (namespace) (kube_pod_status_phase{phase=\"Running\", namespace=~\"gpu|service|db\"} == 1) > bool 0\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "총 CPU 사용량",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "총 메모리 사용량",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "RAM Usage"
    }
   ]
  },
  {
   "title": "CPU 사용량",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  rate(container_cpu_usage_seconds_total{\n    image!=\"\", container!=\"POD\",\n    namespace=~\"gpu\"\n  }[1m])\n)",
     "legendFormat": "GPU"
    },
    {
     "expr": "sum by (namespace) (\n  rate(container_cpu_usage_seconds_total{\n    image!=\"\", container!=\"POD\",\n    namespace=~\"service\"\n  }[1m])\n)",
     "legendFormat": "Service"
    },
    {
     "expr": "sum by (namespace) (\n  rate(container_cpu_usage_seconds_total{\n    image!=\"\", container!=\"POD\",\n    namespace=~\"db\"\n  }[1m])\n)",
     "legendFormat": "DB"
    }
   ]
  },
  {
   "title": "메모리 사용량 ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  container_memory_working_set_bytes{\n    image!=\"\", container!=\"POD\",\n    namespace=~\"gpu\"\n  }\n)",
     "legendFormat": "GPU"
    },
    {
     "expr": "sum by (namespace) (\n  container_memory_working_set_bytes{\n    image!=\"\", container!=\"POD\",\n    namespace=~\"service\"\n  }\n)",
     "legendFormat": "Service"
    },
    {
     "expr": "sum by (namespace) (\n  container_memory_working_set_bytes{\n    image!=\"\", container!=\"POD\",\n    namespace=~\"db\"\n  }\n)",
     "legendFormat": "DB"
    }
   ]
  },
  {
   "title": "네임 스페이스별 파드 개수",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"gpu\"})",
     "legendFormat": "GPU"
    },
    {
     "expr": "count(kube_pod_info{namespace=\"db\"})",
     "legendFormat": "DB"
    },
    {
     "expr": "count(kube_pod_info{namespace=\"service\"})",
     "legendFormat": "Service"
    }
   ]
  },
  {
   "title": "노드 가동 시간",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "유휴 CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu 총 코어 수",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "유휴 메모리",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "총 메모리",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "네트워크 트래픽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(container_network_receive_bytes_total{namespace=\"service\", pod=~\"net-srv.*\"}[1m])\n)\n+\nsum(\n  rate(container_network_transmit_bytes_total{namespace=\"service\", pod=~\"net-srv.*\"}[1m])\n) ",
     "legendFormat": "서버 트래픽"
    },
    {
     "expr": "sum(\n  rate(container_network_receive_bytes_total{namespace=\"service\", pod=~\"net-gen.*\"}[1m])\n)\n+\nsum(\n  rate(container_network_transmit_bytes_total{namespace=\"service\", pod=~\"net-gen.*\"}[1m])\n)",
     "legendFormat": "클라이언트 트래픽"
    }
   ]
  },
  {
   "title": "디스크 사용량",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes/sec (IEC)" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  rate(node_disk_written_bytes_total[5m])\n) / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}