{
 "title": "k8s dashboard",
 "tags": [
  "k8s",
  "node",
  "monitoring"
 ],
 "time": { "from": "now-10m", "to": "now" },
 "panels": [
  {
   "title": "CPU 사용량 %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "RAM 사용량",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "RAM Usage"
    }
   ]
  },
  {
   "title": "Pod 갯수",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"default\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "List of Pods on node (default)",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"default\"} "
    }
   ]
  },
  {
   "title": "cpu 사용량",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu 총 코어 수",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM 사용량",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "총 RAM 량",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "node_uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total[5m])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "RAM Total" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "RAM Free" },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "RAM Cache" },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "RAM Buffer" },
    { "expr": "node_memory_SwapTotal_bytes", "legendFormat": "SWAP Total" },
    { "expr": "node_memory_SwapFree_bytes", "legendFormat": "SWAP Free" }
   ]
  }
 ]
}